spring.application.name=discountCode

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/discount_code}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:discount_code}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:discount_code}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
